#!/usr/bin/env python3
"""
Memory Sync - Status and legacy sync operations.

Primary usage:
    # Check status
    python3 scripts/sync.py --project "llm_memory" --status

    # Mark sync complete (creates heartbeat/token)
    python3 scripts/sync.py --project "llm_memory" --complete

For extraction workflow, use:
    - extract.md / extract_pending.py (find pending)
    - validate_extraction.py (validate)
    - store_extraction.py (store)

Legacy operations (--show, --store) still supported but prefer extract.md workflow.
"""

import argparse
import sys
import os
import subprocess
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from tools.console_utils import safe_print, setup_console_encoding
from tools.config import load_config

# Setup console encoding for Windows
setup_console_encoding()


SYNC_EXAMPLES = """
Examples:
  # Check status (see status.md)
  python scripts/sync.py --project llm_memory --status

  # Mark sync complete (creates heartbeat + token)
  python scripts/sync.py --project llm_memory --complete --agent auggie

  # Show unprocessed interactions
  python scripts/sync.py --project llm_memory --show --limit 10

Note: For extraction workflow, use extract.md instead of --store.
"""


class SyncArgumentParser(argparse.ArgumentParser):
    """Custom parser that prints examples on error."""
    def error(self, message):
        self.print_usage(sys.stderr)
        self.exit(2, f"{self.prog}: error: {message}\n{SYNC_EXAMPLES}")


def fail_preflight(message: str):
    safe_print(f"[ERROR] {message}")
    sys.exit(1)


def sync_show(python_path: str, project_name: str, limit: int = None, include_confidential: bool = False):
    """Show unprocessed interactions."""
    cmd = [
        python_path, "scripts/sync_interactive.py",
        "--project", project_name
    ]

    if limit:
        cmd.extend(["--limit", str(limit)])

    if include_confidential:
        cmd.append("--include-confidential")

    result = subprocess.run(cmd)
    return result.returncode


def sync_store(
    python_path: str,
    project_name: str,
    extraction_file: str,
    skip_quality_check: bool = False,
    require_quality_review: bool = False
):
    """Store extraction results."""
    if not Path(extraction_file).exists():
        fail_preflight(f"Extraction file not found: {extraction_file}")

    cmd = [
        python_path, "scripts/store_extraction.py",
        "--project", project_name,
        "--extraction-file", extraction_file
    ]

    if skip_quality_check:
        cmd.append("--skip-quality-check")
    if require_quality_review:
        cmd.append("--require-quality-review")

    result = subprocess.run(cmd)
    return result.returncode


# Token file for pre-commit sync gate
SYNC_TOKEN_FILE = "tmp/_____COMMIT_BLOCKED_UNTIL_SYNC_COMPLETES_____.tmp"


def create_sync_token(project_name: str = "", agent: str = ""):
    """
    Create the sync token file for pre-commit hook validation.

    This is the SOLE location where tokens are created.
    store_extraction.py does NOT create tokens - sync.py owns this.
    """
    from datetime import datetime

    token_path = Path(SYNC_TOKEN_FILE)
    token_path.parent.mkdir(parents=True, exist_ok=True)

    now = datetime.now().isoformat()
    content = f"""Sync Token - Pre-Commit Sync Gate
==================================
Created: {now}
Project: {project_name or 'unknown'}
Agent: {agent or 'unknown'}

This file is auto-generated by sync.py --complete.
It will be deleted by the pre-commit hook on successful commit.
If you see this file lingering, something went wrong - re-run sync.md.
"""
    token_path.write_text(content)
    safe_print(f"[OK] Created sync token: {SYNC_TOKEN_FILE}")


def create_heartbeat_batch(project_name: str, agent: str = "unknown", model: str = ""):
    """
    Create a heartbeat ExtractionBatch when unprocessed == 0.
    This is a semantic sync checkpoint - proves sync was run even if nothing to extract.
    """
    from tools.graph_db import GraphDatabase

    config = load_config(project_name=project_name)
    graph_db = GraphDatabase(config.get_graph_db_path())

    batch_uuid = graph_db.create_extraction_batch(
        project_name=project_name,
        extracted_by_agent=agent,
        extracted_by_model=model,
        extraction_version="heartbeat",
        extraction_commit="sync-checkpoint",
        source_interaction_uuids=[],
        source_interaction_hashes=[],
        created_entity_uuids=[],
        created_relationship_uuids=[],
        result="heartbeat"
    )

    graph_db.close()
    safe_print(f"[OK] Created heartbeat batch: {batch_uuid}")
    return batch_uuid


def sync_complete(project_name: str, agent: str = "unknown", model: str = ""):
    """
    Mark sync as complete. Creates heartbeat if nothing to extract, creates token.
    This is the primary entry point for completing a sync cycle.
    """
    from tools.sql_db import SQLDatabase

    config = load_config(project_name=project_name)
    sql_db = SQLDatabase(config.get_sql_db_path())
    counts = sql_db.get_interaction_counts(project_name)

    if counts["unprocessed"] == 0:
        # Nothing to extract - create heartbeat as semantic checkpoint
        create_heartbeat_batch(project_name, agent, model)

    # Always create token after successful sync (sync.py is SOLE token owner)
    create_sync_token(project_name=project_name, agent=agent)

    safe_print(f"[OK] Sync complete for project '{project_name}'")


def sync_status(project_name: str):
    """Show sync status."""
    from tools.sql_db import SQLDatabase

    config = load_config(project_name=project_name)
    sql_db = SQLDatabase(config.get_sql_db_path())
    counts = sql_db.get_interaction_counts(project_name)

    if counts["total"] == 0:
        safe_print(f"[ERROR] No interactions found for project '{project_name}'")
        return

    total = counts["total"]
    processed = counts["processed"]
    unprocessed = counts["unprocessed"]

    safe_print("=" * 60)
    safe_print(f"[DATA] Memory Status for '{project_name}'")
    safe_print("=" * 60)
    safe_print(f"Total interactions:       {total}")
    safe_print(f"Processed:                {processed}")
    safe_print(f"Unprocessed:              {unprocessed}")
    safe_print()

    if unprocessed > 0:
        safe_print(f"[WARNING]  {unprocessed} interaction(s) pending extraction")
        safe_print()
        safe_print("Next steps:")
        safe_print(f"  Follow extract.md, or run:")
        safe_print(f"    python scripts/extract_pending.py --project \"{project_name}\"")
    else:
        safe_print("[OK] All interactions processed!")

    safe_print()


if __name__ == "__main__":
    parser = SyncArgumentParser(
        description="Memory sync utility",
        epilog=SYNC_EXAMPLES,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--project", required=True, help="Project name")

    # Actions
    parser.add_argument("--show", action="store_true", help="Show unprocessed interactions")
    parser.add_argument("--store", metavar="FILE", help="Store extraction results from FILE")
    parser.add_argument("--status", action="store_true", help="Show sync status")
    parser.add_argument("--complete", action="store_true",
                        help="Mark sync as complete (creates heartbeat if needed, creates token)")

    # Options
    parser.add_argument("--limit", type=int, help="Limit number of interactions (for --show)")
    parser.add_argument("--include-confidential", action="store_true", help="Include confidential (for --show)")
    parser.add_argument("--skip-quality-check", action="store_true", help="Pass through to store_extraction.py")
    parser.add_argument("--require-quality-review", action="store_true", help="Pass through to store_extraction.py")
    parser.add_argument("--agent", default="unknown", help="Agent name for heartbeat (for --complete)")
    parser.add_argument("--model", default="", help="Model name for heartbeat (for --complete)")

    args = parser.parse_args()
    if args.skip_quality_check and args.require_quality_review:
        fail_preflight("Cannot use --skip-quality-check and --require-quality-review together")

    config = load_config(project_name=args.project)
    python_path = config.get_python_path()

    if args.show:
        sys.exit(sync_show(python_path, args.project, args.limit, args.include_confidential))
    elif args.store:
        sys.exit(sync_store(
            python_path,
            args.project,
            args.store,
            skip_quality_check=args.skip_quality_check,
            require_quality_review=args.require_quality_review
        ))
    elif args.complete:
        sync_complete(args.project, args.agent, args.model)
    elif args.status:
        sync_status(args.project)
    else:
        # Default: show status
        sync_status(args.project)
